<?php
/**
 * User: Evan Lee
 * Date: 2017/2/20
 * Time: 11:14
 */

namespace app\worker\utils;


use think\gateway\Events;

class EventHandler extends Events
{

    /**
     * @param $client_id
     * @param $message
     */
    public static function processMessage($client_id, $message)
    {
        parent::processMessage($client_id, $message); // TODO: Change the autogenerated stub
    }
}